### ISSUE TITLE
DISCORD_INVITE_LINK env var nao deveria ser obrigatoria

### ISSUE THREAD

**Issue by vcaldo** [vcaldo/cerverox9#11]
Mudar de `os.LookupEnv` para `os.GetEnv`

https://github.com/vcaldo/cerverox9/blob/7857210272d9da7453b70e18fb3f92b2efc7182a/telegram/pkg/handlers/handlers.go#L30

E testa pra ver o q acontece quando o env var nao tiver setada, pra isso apaga ela no secrets.env

**Comment by vcaldo** [comment]
da uma olhada tambem nas outras env vars que nao precisariam ser obrigatorias.

**Comment by gilson728** [comment]
Já corrigi neste pull request:
https://github.com/vcaldo/cerverox9/pull/13
